# Generated by Django 4.0.4 on 2022-09-04 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TOdoList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=30, unique=True)),
                ('Desc', models.CharField(max_length=300)),
                ('time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
