# Generated by Django 4.0.4 on 2022-09-05 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_todolist_comlete'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todolist',
            old_name='comlete',
            new_name='completed',
        ),
        migrations.RenameField(
            model_name='todolist',
            old_name='Desc',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='todolist',
            old_name='Title',
            new_name='title',
        ),
    ]
